"""Generate the hot-path kernel parity fixtures.

The five hot-path operations (encode, recall/cosineRecall, etch/holographic
update, evolve/evolveScore, homeostasis) must compute byte-identical results in
the Python reference (`mcop_cuda_server/kernels.py`) and the TypeScript
reference (`src/hardware/referenceKernels.ts`) that the `HotPathRouter` runs on
its CPU path. This script runs the Python reference over a fixed set of inputs
and writes the inputs + expected outputs to ``hotPathKernels.golden.json``.

The Jest test ``src/__tests__/hotPathParity.test.ts`` loads the same file and
asserts the TypeScript reference reproduces every expected output. If either
runtime drifts, that side's test fails — this is the parity baseline the
conformance spec (advance #4) will build on.

Re-generate after changing any kernel::

    python3 tests/parity/generate_hotpath_fixtures.py

Do not edit the JSON by hand — re-run this script.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "mcop_cuda_server"))

from kernels import default_registry as R  # noqa: E402

CASES = [
    {"op": "encode", "kernel": "encode", "input": {"tensor": [0.0, 1.0, -1.0, 2.5], "bias": 0.1}},
    {"op": "encode", "kernel": "encode", "input": {"tensor": [], "bias": 0.0}},
    {
        "op": "recall",
        "kernel": "cosineRecall",
        "input": {"query": [1.0, 0.0, 1.0], "library": [[1.0, 0.0, 1.0], [0.0, 1.0, 0.0], [2.0, 0.0, 2.0]]},
    },
    {
        "op": "etch",
        "kernel": "holographicUpdate",
        "input": {"context": [1.0, 2.0, 0.0], "synthesis": [3.0, 4.0]},
    },
    {
        "op": "evolve",
        "kernel": "evolveScore",
        "input": {"candidates": [{"score": 1.0, "vector": [3.0, 4.0]}, {"score": 0.5}, 2.0]},
    },
    {
        "op": "homeostasis",
        "kernel": "homeostasis",
        "input": {"state": [2.0, -2.0, 0.5], "decay": 0.98, "floor": -1.0, "ceil": 1.0},
    },
    {
        "op": "homeostasis",
        "kernel": "homeostasis",
        "input": {"state": [0.25, -0.25]},
    },
]


def main() -> None:
    cases = []
    for case in CASES:
        expected = R.dispatch(case["kernel"], case["input"])
        cases.append({"op": case["op"], "kernel": case["kernel"], "input": case["input"], "expected": expected})
    out = {
        "_comment": "Generated by tests/parity/generate_hotpath_fixtures.py — do not edit by hand.",
        "cases": cases,
    }
    path = Path(__file__).resolve().parent / "hotPathKernels.golden.json"
    path.write_text(json.dumps(out, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(cases)} cases)")


if __name__ == "__main__":
    main()
