// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Kevin John Kull (Kuonirad) and KullAILABS MCOP Framework contributors
/**
 * Byte-identity guardian — the headline claim, made checkable.
 *
 * The cognition-state digest is `SHA-256(RFC-8785-canonical-JSON(payload))` —
 * the substrate under every MCOP provenance hash. This test recomputes that
 * digest for a shared fixture through **three independent JavaScript SHA-256
 * implementations** and asserts they equal each other *and* the Python golden
 * (`tests/parity/byteIdentity.golden.json`, generated by
 * `tests/parity/generate_byte_identity_fixtures.py`):
 *
 *   1. node-crypto       — `canonicalEncoding.canonicalDigest` (Node `crypto`)
 *   2. portable-js       — `reasoningReceipts.leafEntryForClaim` (pure-JS SHA-256)
 *   3. webcrypto-subtle  — W3C WebCrypto `subtle.digest`
 *   4. python-hashlib    — the golden
 *
 * Four runtimes, one digest, byte for byte. It also emits the publishable
 * manifest `docs/benchmarks/byte-identity-manifest.json`.
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import * as path from 'node:path';
import { createHash, webcrypto } from 'node:crypto';
import canonicalize from 'canonicalize';

import { canonicalDigest } from '../core/canonicalEncoding';
import { leafEntryForClaim } from '../core/reasoningReceipts';
import { utf8Bytes, bytesToHex } from '../core/universalCrypto';

interface Golden {
  schema: string;
  fixture: unknown[];
  digests: string[];
  consensusRoot: string;
}

const REPO_ROOT = path.resolve(__dirname, '..', '..');
const GOLDEN_PATH = path.join(REPO_ROOT, 'tests', 'parity', 'byteIdentity.golden.json');
const golden: Golden = JSON.parse(readFileSync(GOLDEN_PATH, 'utf8'));

/** Node native `crypto.createHash`. */
function nodeCryptoDigest(payload: unknown): string {
  return canonicalDigest(payload);
}

/** Portable pure-JS SHA-256 (the in-browser / edge substrate). */
function portableDigest(payload: unknown): string {
  return leafEntryForClaim(payload);
}

/** W3C WebCrypto `subtle.digest` over the same canonical bytes. */
async function webCryptoDigest(payload: unknown): Promise<string> {
  const raw = canonicalize(payload) ?? '{}';
  const bytes = new Uint8Array(utf8Bytes(raw)); // ArrayBuffer-backed copy for WebCrypto
  const buf = await webcrypto.subtle.digest('SHA-256', bytes);
  return bytesToHex(new Uint8Array(buf));
}

describe('Byte-identity across four runtimes', () => {
  test('the three JS runtimes agree with each other and with Python, per payload', async () => {
    for (let i = 0; i < golden.fixture.length; i += 1) {
      const payload = golden.fixture[i];
      const node = nodeCryptoDigest(payload);
      const portable = portableDigest(payload);
      const web = await webCryptoDigest(payload);
      const python = golden.digests[i];
      expect(node).toBe(python);
      expect(portable).toBe(python);
      expect(web).toBe(python);
    }
  });

  test('the serialisation edge cases (signed zero, 1e21, non-BMP) are byte-identical', async () => {
    // The payload where naive JSON.stringify vs json.dumps diverge — the whole
    // point of RFC 8785. If any runtime drifts here, the claim is false.
    const idx = golden.fixture.findIndex(
      (p) => (p as { subsystem?: string }).subsystem === 'serialisation-edges',
    );
    expect(idx).toBeGreaterThanOrEqual(0);
    const payload = golden.fixture[idx];
    expect(nodeCryptoDigest(payload)).toBe(golden.digests[idx]);
    expect(portableDigest(payload)).toBe(golden.digests[idx]);
    expect(await webCryptoDigest(payload)).toBe(golden.digests[idx]);
  });

  test('the consensus root reproduces from the JS side', () => {
    const jsDigests = golden.fixture.map((p) => nodeCryptoDigest(p));
    expect(jsDigests).toEqual(golden.digests);
    const consensus = createHash('sha256').update(jsDigests.join('\n')).digest('hex');
    expect(consensus).toBe(golden.consensusRoot);
  });

  test('emits the four-runtime byte-identity manifest', async () => {
    const perPayload = await Promise.all(
      golden.fixture.map(async (payload, i) => {
        const node = nodeCryptoDigest(payload);
        const portable = portableDigest(payload);
        const web = await webCryptoDigest(payload);
        const python = golden.digests[i];
        const agree = node === python && portable === python && web === python;
        return {
          subsystem: (payload as { subsystem?: string }).subsystem ?? `payload-${i}`,
          digest: python,
          agreement: { 'node-crypto': node === python, 'portable-js': portable === python, 'webcrypto-subtle': web === python, 'python-hashlib': true },
          allAgree: agree,
        };
      }),
    );
    const manifest = {
      schema: 'mcop-byte-identity/1.0',
      generatedBy: 'src/__tests__/byteIdentity.test.ts',
      note: 'SHA-256(RFC-8785-canonical-JSON(payload)) — the substrate under every MCOP provenance hash.',
      runtimes: ['node-crypto', 'portable-js', 'webcrypto-subtle', 'python-hashlib'],
      consensusRoot: golden.consensusRoot,
      allRuntimesAgree: perPayload.every((p) => p.allAgree),
      perPayload,
    };
    expect(manifest.allRuntimesAgree).toBe(true);
    const outDir = path.join(REPO_ROOT, 'docs', 'benchmarks');
    mkdirSync(outDir, { recursive: true });
    writeFileSync(
      path.join(outDir, 'byte-identity-manifest.json'),
      `${JSON.stringify(manifest, null, 2)}\n`,
    );
  });
});
