{{- if .Values.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcop-ledger.fullname" . }}-secret
  labels:
    {{- include "mcop-ledger.labels" . | nindent 4 }}
type: Opaque
stringData:
  apiKey: {{ .Values.apiKey | quote }}
{{- end }}
